version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: simulacro_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Qwe.123*
      MYSQL_DATABASE: simulacroWA
      MYSQL_USER: appuser
      MYSQL_PASSWORD: Qwe.123*
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Simulacro-HU3.Api/Dockerfile
    container_name: simulacro_api  
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: "Server=mysql;Database=simulacroudb;user=root;password=Qwe.123*;"
      Jwt__Key: "CLAVE_SUPER_SECRETA_CAMBIAR"
      ASPNETCORE_URLS: "http://+:80"
    ports:
      - "8080:80"
    restart: always

  adminer:
    image: adminer
    container_name: simulacro_adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  mysql_data:
