version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: WebApi-HU3.Api/Dockerfile
    container_name: WebApi-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=server=webapi-nebula-nebula-riwi.k.aivencloud.com;database=defaultdb;user=avnadmin;password=;SslMode=Required;
    networks:
      - school_network

  adminer:
    image: adminer
    container_name: webapi-adminer
    restart: always
    ports:
      - "8081:8080"
    networks:
      - school_network

networks:
  school_network:
